### Get all items
GET http://localhost:3000/

### Create item
POST http://localhost:3000/
Content-Type: application/json

{
    "item": "add new item"
}

### Delete item
DELETE http://localhost:3000/4
